[17.0][MIG] mrp_bom_structure_xlsx_level 1
OCA/manufacture-reporting pull request #126
Opened 2024-04-18 07:35 UTC by AnaisLForgeFlow

Standard Migration

@ForgeFlow

2024-04-18 14:05 UTC, LoisRForgeFlow requested changes
The module is available in v16: https://github.com/OCA/manufacture-reporting/tree/16.0/mrp_bom_structure_xlsx_level_1

You need to always migrate from the latest version available.

2024-04-19 10:56 UTC, GuillemCForgeFlow approved these changes
LGTM! 👍🏿

2024-04-19 10:56 UTC, GuillemCForgeFlow commented on mrp_bom_structure_xlsx_level_1/readme/DESCRIPTION.md
> +.XLSX format.
Perhaps this definition can be improved a little. What do you think about adding this?

> If you have a Bill of Materials (`A`) for which one of the Components also has a Bill of Materials (`B`). The report will only display the Components within the first level for the selected Bill of Materials (`A`), but not the Components from the Bill of Materials (`B`).

2024-04-22 12:40 UTC, LoisRForgeFlow approved these changes
LGTM to me know :+1:

2024-04-22 12:40 UTC, LoisRForgeFlow commented
/ocabot merge nobump

2024-04-22 12:45 UTC, merged

2025-07-28 10:05 UTC, LoisRForgeFlow commented
/ocabot migration mrp_bom_structure_xlsx_level_1