[ADD] module 'mrp_bom_structure_xls'
OCA/manufacture-reporting pull request #8
Opened 2015-05-11 10:39 UTC by jbeficent

This module was written to extend the MRP capabilities of Odoo, and
allows users to export the BOM structure to MS Excel .XLS format.

2015-05-11 11:57 UTC, jbeficent commented
Travis fails due to depending library "report_xls" is not in this repo. Not sure how to proceed in this case..

2015-05-11 12:24 UTC, tafaRU commented
@jbeficent see https://github.com/Eficent/manufacture-reporting/pull/1, it should fix the error in travis build.

2015-05-11 12:49 UTC, jbeficent commented
Thanks @tafaRU How to re-run Travis?

2015-05-11 12:52 UTC, tafaRU commented
@jbeficent I think it's enough to merge the PR.

2015-11-25 11:36 UTC, jbeficent commented
@tafaRU Not sure why runbot would fail on this one with message "ImportError: No module named report_xls" if the oca-dependencies have been added. Any clues?

2015-11-25 11:56 UTC, tafaRU commented
@jbeficent oca-dependecies fixed travis build, runbot build error I don't think is related.
I suppose the problem should be fixed adding the OCA/reporting-engine repo to the manufacture-reporting runbot. Please send a mail to contribute@odoo-community.org  or ask to @gurneyalex to #oca

2015-11-25 12:04 UTC, gurneyalex commented
@jbeficent I updated the runbot config, and restarted a build. 

thanks for the notice.

2015-11-25 12:11 UTC, jbeficent commented
Thanks @gurneyalex ! However I see that in the PR runbot is red, not yellow. Is that ok?

2015-11-25 12:48 UTC, gurneyalex commented
@jbeficent can't seem to restart. Can you run `git commit --amend` and `git push -f` to force a rebuild?

2015-11-25 12:51 UTC, jbeficent commented
@gurneyalex Done. But sems that runbot and Travis are not starting.

2015-11-25 17:14 UTC, jbeficent commented
@gurneyalex Thanks. It's now green. Coveralls is red, but not sure what is it's role.

2015-11-27 13:25 UTC, gurneyalex commented
@jbeficent Coveralls role is red because you should add a simple automated test to the module exercising the code by generating a report. You'll get bonus points in my view if you also check the contents of the report. But just generating the report will ensure the code runs and improve the test coverage of the project.

2016-03-18 11:41 UTC, pedrobaeza commented
Any news on this?

2016-08-09 14:23 UTC, gurneyalex commented
:+1:

2016-10-26 23:34 UTC, jbeficent commented
This one is ready to be merged. Anyone can quickly check and approve?

2016-10-27 09:04 UTC, pedrobaeza requested changes

2016-10-27 09:04 UTC, pedrobaeza commented on mrp_bom_structure_xls/README.rst
> +Export BOM Structure to Excel
Please update template to the newest one.

2016-10-27 09:04 UTC, pedrobaeza commented on mrp_bom_structure_xls/__init__.py
> +##############################################################################
Short headers

2016-10-27 09:04 UTC, pedrobaeza commented on mrp_bom_structure_xls/__openerp__.py
> +    'version': '1.0',
8.0.1.0.0

2016-10-27 09:04 UTC, pedrobaeza commented on mrp_bom_structure_xls/__openerp__.py
> +    'author': "Eficent",
Add OCA

2017-01-18 08:58 UTC, lreficent commented on mrp_bom_structure_xls/__openerp__.py
> +    'author': "Eficent",
Ok, We will attend all this.

2017-01-18 09:19 UTC, lreficent commented
why are there no running test (travis, runbot...) for this PR?

2017-01-18 09:22 UTC, jbeficent commented
Because it is an export to XLS. Not sure how it would be possible to.add

El 18 ene. 2017 2:19 a. m., "Lois Rilo" <notifications@github.com> escribió:

> why are there no running test (travis, runbot...) for this PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/OCA/manufacture-reporting/pull/8#issuecomment-273423613>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHU_Vm_J1CbRqYq2lSKQu2MKMioUHPs4ks5rTdkmgaJpZM4EWceH>
> .
>

2017-01-19 09:44 UTC, aheficent commented
coveralls is not referring any file of this PR

2017-01-19 12:52 UTC, jbeficent commented
@gurneyalex @moylop260  Seems that runbot is not running on this repo. Do you know why?

2017-01-19 15:10 UTC, moylop260 commented
@jbeficent 
The issue is https://github.com/OCA/runbot-addons/issues/115

2017-01-19 20:47 UTC, jbeficent commented
Thanks @moylop260. Created PR https://github.com/OCA/manufacture-reporting/pull/15

2017-01-22 08:42 UTC, gurneyalex commented
PR #15 merged. You need to rebase your PRs to get runbot builds.

2017-01-25 17:06 UTC, jbeficent commented on mrp_bom_structure_xls/README.rst
> +Installation
Remove this section, as it is not used

2017-01-25 17:06 UTC, jbeficent commented on mrp_bom_structure_xls/README.rst
> +Configuration
Remove this section, as it is not used

2017-01-25 20:48 UTC, tafaRU commented on mrp_bom_structure_xls/__openerp__.py
> +    'test': [],
Please remove empty keys

2017-01-25 21:49 UTC, jbeficent commented
@tafaRU @pedrobaeza This one is ready to merge.

2017-01-26 09:07 UTC, AaronHForgeFlow approved these changes
Tested on runbot :+1:

2017-01-26 09:16 UTC, tafaRU approved these changes
Thanks!

2017-01-26 14:06 UTC, moylop260 approved these changes

2017-01-26 15:13 UTC, LoisRForgeFlow approved these changes
Tested :+1:

2017-01-26 15:57 UTC, merged